# Generated by Django 4.1.4 on 2022-12-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('fromNode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fromGraph', to='graphs.node')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='graphs.graphgroup')),
                ('toNode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='toGraph', to='graphs.node')),
            ],
            options={
                'unique_together': {('fromNode', 'toNode')},
            },
        ),
    ]
