# Generated by Django 4.1.4 on 2022-12-21 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graph',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='graph',
            name='fromNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nodes', to='graphs.node'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='toNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='toNode', to='graphs.node'),
        ),
        migrations.AlterUniqueTogether(
            name='graph',
            unique_together={('groups', 'fromNode', 'toNode')},
        ),
    ]
